services:
  - type: web
    name: ikms-context-critic
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.app.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_EMBEDDING_MODEL_NAME
        value: text-embedding-ada-002
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: ikms-index